/**
 * SDK Generator
 * 
 * Wraps openapi-generator to generate client SDKs from OpenAPI specs
 */

import { execSync, spawn } from 'child_process';
import * as fs from 'fs';
import * as path from 'path';
import { SupportedLanguage } from '../types';

export interface SDKGeneratorOptions {
  specPath: string;
  outputDir: string;
  language: SupportedLanguage;
  packageName?: string;
}

export class SDKGenerator {
  private generatorLanguageMap: Record<SupportedLanguage, string> = {
    java: 'java',
    typescript: 'typescript-fetch',
    python: 'python'
  };
  
  private additionalProperties: Record<SupportedLanguage, Record<string, string>> = {
    java: {
      library: 'okhttp-gson',
      dateLibrary: 'java8',
      useRuntimeException: 'true'
    },
    typescript: {
      supportsES6: 'true',
      npmName: '@sdk/client'
    },
    python: {
      packageName: 'sdk_client'
    }
  };
  
  /**
   * Generate SDK from OpenAPI specification
   */
  async generate(options: SDKGeneratorOptions): Promise<void> {
    // Validate inputs
    if (!fs.existsSync(options.specPath)) {
      throw new Error(`OpenAPI spec not found: ${options.specPath}`);
    }
    
    const generatorName = this.generatorLanguageMap[options.language];
    if (!generatorName) {
      throw new Error(`Unsupported language: ${options.language}`);
    }
    
    // Prepare output directory
    if (!fs.existsSync(options.outputDir)) {
      fs.mkdirSync(options.outputDir, { recursive: true });
    }
    
    // Build generator command
    const additionalProps = { ...this.additionalProperties[options.language] };
    
    if (options.packageName) {
      if (options.language === 'java') {
        additionalProps['invokerPackage'] = options.packageName;
        additionalProps['apiPackage'] = `${options.packageName}.api`;
        additionalProps['modelPackage'] = `${options.packageName}.model`;
      } else if (options.language === 'python') {
        additionalProps['packageName'] = options.packageName.replace(/\./g, '_');
      }
    }
    
    const additionalPropsStr = Object.entries(additionalProps)
      .map(([key, value]) => `${key}=${value}`)
      .join(',');
    
    // Use openapi-generator-cli
    const args = [
      'generate',
      '-i', options.specPath,
      '-g', generatorName,
      '-o', options.outputDir,
      '--additional-properties', additionalPropsStr
    ];
    
    await this.runGenerator(args);
    
    // Post-process for specific languages
    await this.postProcess(options);
  }
  
  /**
   * Run openapi-generator using npx
   */
  private async runGenerator(args: string[]): Promise<void> {
    return new Promise((resolve, reject) => {
      const command = 'npx';
      const fullArgs = ['@openapitools/openapi-generator-cli', ...args];
      
      const proc = spawn(command, fullArgs, {
        stdio: ['pipe', 'pipe', 'pipe'],
        shell: true
      });
      
      let stdout = '';
      let stderr = '';
      
      proc.stdout.on('data', (data) => {
        stdout += data.toString();
      });
      
      proc.stderr.on('data', (data) => {
        stderr += data.toString();
      });
      
      proc.on('close', (code) => {
        if (code === 0) {
          resolve();
        } else {
          reject(new Error(`openapi-generator failed with code ${code}: ${stderr || stdout}`));
        }
      });
      
      proc.on('error', (err) => {
        reject(new Error(`Failed to run openapi-generator: ${err.message}`));
      });
    });
  }
  
  /**
   * Post-process generated SDK
   */
  private async postProcess(options: SDKGeneratorOptions): Promise<void> {
    const readmePath = path.join(options.outputDir, 'SDK_README.md');
    
    const readmeContent = `# Generated SDK

This SDK was generated by Spec-Kit using openapi-generator.

## Language
${options.language}

## Package
${options.packageName || 'default'}

## Usage

### Java

\`\`\`java
import ${options.packageName || 'com.example.client'}.api.*;
import ${options.packageName || 'com.example.client'}.model.*;

// Initialize API client
ApiClient client = new ApiClient();
client.setBasePath("http://localhost:8080/api/v1");

// Use the API
DefaultApi api = new DefaultApi(client);
\`\`\`

### TypeScript

\`\`\`typescript
import { Configuration, DefaultApi } from './sdk';

const config = new Configuration({
  basePath: 'http://localhost:8080/api/v1'
});

const api = new DefaultApi(config);
\`\`\`

## Important

> ⚠️ This SDK is auto-generated. Do not modify directly.
> To update the SDK, modify the OpenAPI spec and regenerate.
`;
    
    fs.writeFileSync(readmePath, readmeContent);
  }
  
  /**
   * Check if openapi-generator is available
   */
  async checkAvailability(): Promise<boolean> {
    try {
      execSync('npx @openapitools/openapi-generator-cli version', {
        stdio: 'pipe'
      });
      return true;
    } catch {
      return false;
    }
  }
}
